FROM postgres:13.8-alpine3.16

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=aictforum

COPY ./schemas/forum_schema/forum_schema.sql /docker-entrypoint-initdb.d/forum_schema.sql
COPY ./schemas/forum_schema/procedures /docker-entrypoint-initdb.d/procedures
